backend:
  name: github
  repo: LovroHodak/TypeformZapierNetlifyCMS
  branch: main
  #change the name of repo to yours

media_folder: "public/images"
public_folder: "images"
publish_mode: editorial_workflow  

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    files:
      - file: src/content/testing.json
        name: testing
        label: 'Testing'
        fields:
          -label: "Testing"
           name: testing
           widget: list
           fields:
            - label: "Layout"
              name: label
              widget: hidden
              default: blog
            - label: "Title"
              name: title
              widget: string
            - label: "Publish Date"
              name: date
              widget: datetime
            - label: "Featured Image"
              name: thumbnail
              widget: image
            - label: "Rating (scale of 1-5)"
              name: rating
              widget: number
            - label: "Body"
              name: body
              widget: markdown
              

   

  